//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Common.Errors {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Common.Errors.ErrorMessages", typeof(ErrorMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field {field} is required..
        /// </summary>
        internal static string e11010001 {
            get {
                return ResourceManager.GetString("e11010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Subfield {subfield} is required in the {type} named {field}..
        /// </summary>
        internal static string e11010002 {
            get {
                return ResourceManager.GetString("e11010002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with value {value} must contain at least {requirement}..
        /// </summary>
        internal static string e12010001 {
            get {
                return ResourceManager.GetString("e12010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with value {value} can only contain {values}..
        /// </summary>
        internal static string e12010002 {
            get {
                return ResourceManager.GetString("e12010002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with value {value} doesn&apos;t meet the requirements of {count} digits..
        /// </summary>
        internal static string e12010003 {
            get {
                return ResourceManager.GetString("e12010003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with value {value} doesn&apos;t meet the requirements of {count} digits between the range {min} and {max}..
        /// </summary>
        internal static string e12010004 {
            get {
                return ResourceManager.GetString("e12010004", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with {value} must be an {type}..
        /// </summary>
        internal static string e12020001 {
            get {
                return ResourceManager.GetString("e12020001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with {value} can only contain {types}..
        /// </summary>
        internal static string e12020002 {
            get {
                return ResourceManager.GetString("e12020002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} is not patchable..
        /// </summary>
        internal static string e12030001 {
            get {
                return ResourceManager.GetString("e12030001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} does not supprt the patch action {action}..
        /// </summary>
        internal static string e12030002 {
            get {
                return ResourceManager.GetString("e12030002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} with id {value} doesn&apos;t exists..
        /// </summary>
        internal static string e13010001 {
            get {
                return ResourceManager.GetString("e13010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The action {value} doesn&apos;t exist..
        /// </summary>
        internal static string e13010002 {
            get {
                return ResourceManager.GetString("e13010002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The field {field} is not found..
        /// </summary>
        internal static string e13010003 {
            get {
                return ResourceManager.GetString("e13010003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not authenticated..
        /// </summary>
        internal static string e14010001 {
            get {
                return ResourceManager.GetString("e14010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incorrect authentication credentials specified..
        /// </summary>
        internal static string e14010002 {
            get {
                return ResourceManager.GetString("e14010002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your session or authentication key has expired..
        /// </summary>
        internal static string e14010003 {
            get {
                return ResourceManager.GetString("e14010003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not authorized to view this resource..
        /// </summary>
        internal static string e14020001 {
            get {
                return ResourceManager.GetString("e14020001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not authorized to create this resource..
        /// </summary>
        internal static string e14020002 {
            get {
                return ResourceManager.GetString("e14020002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not authorized to modify this resource..
        /// </summary>
        internal static string e14020003 {
            get {
                return ResourceManager.GetString("e14020003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not authorized to delete this resource..
        /// </summary>
        internal static string e14020004 {
            get {
                return ResourceManager.GetString("e14020004", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not authorized to move this resource..
        /// </summary>
        internal static string e14020005 {
            get {
                return ResourceManager.GetString("e14020005", resourceCulture);
            }
        }
    }
}
